services:
  shop-client:
    container_name: shop-client
    build: ./client
    ports:
      - "5173:80"
  shop-server:
    container_name: shop-server
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=shop-db
    depends_on:
      shop-db:
        condition: service_healthy
  shop-db:
    image: mysql:8.1.0
    container_name: shop-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopeedupe
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./initsql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: