name: Sync to Test Branch

on:
  push:
    branches:
      - server
      - client

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge server branch
        run: |
          git fetch origin server:server
          git merge --no-ff -m "CI: Merge branch 'server' into main" server

      - name: Merge client branch
        run: |
          git fetch origin client:client
          git merge --no-ff -m "CI: Merge branch 'client' into main" client
      
      - name: Push changes
        run: |
          git push origin main